### ISSUE TITLE
ml_pipeline_destroy stops if pipeline has tensor_query_server

### ISSUE THREAD

**Issue by niley7464** [nnstreamer/api#487]
### How to Reproduce

https://github.com/nnstreamer/nnstreamer-example/tree/main/native/example_query_object_detection

1. Run only server with
`$ ./nnstreamer_example_query_object_detection server`

2. Wait for timeout

3. native example stops when stop (NULL state) the pipeline in `ml_pipeline_destroy`

https://github.com/nnstreamer/api/blob/7a3343c196942aa56925765a7bf813875ed63c7c/c/src/ml-api-inference-pipeline.c#L1180

**Comment by wooksong** [comment]
@gichan-jang Do you have any clues about this issue?

**Comment by gichan-jang** [comment]
The tensor_query_serversrc waits for data pop, so changing state from the `PAUSED` to the `NULL` fails.
Need to change release edge handle during `READY` to `PAUSED`.
I will fix it.

**Comment by gichan-jang** [comment]
Resolved. Close this issue.
https://github.com/nnstreamer/nnstreamer/pull/4435
