### ISSUE TITLE
Migrate ML inference API from nnstreamer

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/api#7]
For ubuntu pkg (cc: @gichan-jang @zhoonit @jijoongmoon)
1. setup ppa (ml-api)
2. update dependency to build nnstrainer

For Tizen
Now, please update and test with tizen.org and its infra.

1. Register /platform/core/api/machine-learning into Tizen:Unified build (CC: @again4you ). We will need to setup Coverity/SVACE with it. You may need to start with a "dummy" spec file.
2. Update tizen.org's nnstreamer.git from github.com
3. Send SR of nnstreamer.git
4. Update nnstreamer.git, remove CAPI packages.
5. Send a group SR of nnstreamer.git + api.git (machine learning api in tizen.org)

Be careful with package backward compatibility issues, especially with Tizen Studio.

**Comment by gichan-jang** [comment]
`ml-api` package is published via nnstreamer ppa (bionic and focal).
 - https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa

The focal could not be built because of missing dependencies (nnstreamer focal package build fail caused by python3 test fail)

**Comment by again4you** [comment]
## Progress

- [ ] Register /platform/core/api/machine-learning into Tizen:Unified build.
  * https://bugs.tizen.org/browse/TRE-2632

**Comment by myungjoo** [comment]
Isn't this completed?
